#!/usr/bin/env bash

# symlinks
ln -i -s "$(pwd)"/bash/.bashrc ~/.bashrc
ln -i -s "$(pwd)"/bash/.bash_profile ~/.bash_profile
ln -i -s "$(pwd)"/bash/.bash_aliases ~/.bash_aliases
ln -i -s "$(pwd)"/.vimrc ~/.vimrc
ln -i -s "$(pwd)"/tmux ~/.config/
ln -i -s "$(pwd)"/nvim ~/.config/
ln -i -s "$(pwd)"/alacritty ~/.config/
ln -i -s "$(pwd)"/redshift ~/.config/
ln -i -s "$(pwd)"/.Xmodmap ~/.Xmodmap
ln -i -s "$(pwd)"/lynx ~/.config/
ln -i -s "$(pwd)"/zathura ~/.config/
ln -i -s "$(pwd)"/scripts ~/.local/
