#!/usr/bin/env bash

sudo add-apt-repository ppa:dotnet/backports

sudo apt -y update
sudo apt -y install software-properties-common
sudo apt -y install dotnet-sdk-9.0

# needed for language server in nvim
sudo apt -y install dotnet-sdk-8.0 
