#!/usr/bin/env bash

# package managers
APT=$(which apt)

# nvim
if [[ -n $APT ]]; then
    sudo apt install lua5.1
fi

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
sudo rm -rf "$(pwd)"/nvim-linux-x86_64.tar.gz
