#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install git ripgrep xclip tmux curl tldr 
sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip

git clone https://github.com/junegunn/fzf $HOME/fun/repos/fzf
$HOME/fun/repos/fzf/install
